---
title: "Final Models"
author: "Team 4"
date: "5/20/2022"
output: html_document
---

```{r setup, include=FALSE}
library(fpp)
library(tseries)
library(ggplot2)
library(forecast)
library(urca)
library(TSA)
library(vars)
library(shape)

library(tidyverse)
library(lubridate)
library(clifro)
library(MASS)
library(stringr)
library(zoo)
library(viridis)
library(broom)
library(plotly)
library(knitr)
library(vars)
```

Air temperature (C), Wind Speed (m/s), Wind Direction (degrees from; 0=from N, 90=from E, etc.)

Daily Data
```{r}
df = read.csv(file="all_days.csv",header=T)
head(df)
```
Monthly Data
```{r}
df.agg = read.csv(file="agg.csv",header=T)
head(df.agg)
```

Daily
```{r}
windrose(speed = df$WS,
                 direction =df$WD,
                 speed_cuts = seq(0,10,2),
                 ggtheme='minimal')
```
Monthly
```{r}
windrose(speed = df.agg$m_ws,
                 direction =df.agg$m_wd,
                 speed_cuts = seq(0,10,2),
                 ggtheme='minimal')
```

Monthly
```{r}
df1 <- ts(df.agg$m_ws,start=c(2011,1),frequency=12)
head(df1)
```

```{r}
autoplot(df1,ylab="Monthly Wind Speed")
```

Daily
```{r}
df0 <- ts(df$WS,start=c(2011,1,1),frequency=365)
head(df0)
```

```{r}
autoplot(df0,ylab="Daily Wind Speed")
```

```{r}
train_data = window(df1,start=c(2011,1),end=c(2019,12))
test_data = window(df1,start=c(2020,1),end=c(2021,12))
```

```{r}
autoplot(train_data)
```


```{r}
kpss.test(train_data)
```



```{r}
lambda_train<-BoxCox.lambda(train_data)
t_train<-BoxCox(train_data,lambda_train)
t_test<-BoxCox(test_data,lambda_train)
plot(t_train)
```

```{r}
windtimeseriescomponents <- decompose(train_data)
plot(windtimeseriescomponents)
```


```{r}
tsdisplay(train_data)
```

### Regression model

```{r}
regression.model<-tslm(t_train~trend+season)
summary(regression.model)
```

```{r}
regression.preditct<-forecast(regression.model,h=24)
autoplot(regression.preditct)
```

```{r}
autoplot(test_data) +
  autolayer(InvBoxCox(regression.preditct$mean, lambda_train), series="Regression") +
  ggtitle("Forecast Wind Speed for 2020-2021.") +
  xlab("Year") + ylab("Speed")
```

```{r}
checkresiduals(regression.model)
```
```{r}
accuracy(InvBoxCox(regression.preditct$mean, lambda_train), test_data)
```


### sARIMA model

```{r}
arima.model<-auto.arima(train_data,seasonal=TRUE,lambda = 'auto')
arima.model
```

```{r}
arima.preditct<-forecast(arima.model,h=24)
autoplot(arima.preditct)
```
```{r}
autoplot(arima.preditct) + autolayer(test_data) + ggtitle("Seasonal ARIMA Model Predict")
```
```{r}
autoplot(test_data) +
  autolayer(arima.preditct$mean, series="Seasonal ARIMA model") +
  ggtitle("Forecast Wind Speed for 2020-2021.") +
  xlab("Year") + ylab("Speed")
```


```{r}
checkresiduals(arima.model)
```
```{r}
accuracy(arima.preditct$mean, test_data)
```

### Regression with ARIMA Errors
```{r}
agg.ws = ts(df.agg$m_ws,start=c(2011,1),end = c(2021,12),frequency=12)
agg.at = ts(df.agg$m_at,start=c(2011,1),end = c(2021,12),frequency=12)
agg.wd = ts(df.agg$m_wd,start=c(2011,1),end = c(2021,12),frequency=12)
train.agg.ws = window(agg.ws,start=c(2011,1),end=c(2019,12))
test.agg.ws = window(agg.ws,start=c(2020,1),end=c(2021,12))
train.agg.at = window(agg.at,start=c(2011,1),end=c(2019,12))
test.agg.at = window(agg.at,start=c(2020,1),end=c(2021,12))
train.agg.wd = window(agg.wd,start=c(2011,1),end=c(2019,12))
test.agg.wd = window(agg.wd,start=c(2020,1),end=c(2021,12))
```

```{r}
reg_arima.model <- auto.arima(train.agg.ws, xreg = train.agg.at + train.agg.wd,lambda = 'auto')
reg_arima.model
```

```{r}
checkresiduals(reg_arima.model)
```

```{r}
reg_arima.predict = forecast(reg_arima.model,xreg = test.agg.at + test.agg.wd, h=24)
autoplot(reg_arima.predict)
```

```{r}
autoplot(reg_arima.predict) + autolayer(test_data) + ggtitle("Regression with ARIMA errors model Predict")
```

```{r}
autoplot(test_data) +
  autolayer(reg_arima.predict$mean, series="Regression with ARIMA errors") +
  ggtitle("Forecast Wind Speed for 2020-2021.") +
  xlab("Year") + ylab("Speed")
```



```{r}
accuracy(reg_arima.predict$mean, test_data)
```



### Exponential Smoothing
```{r}
ets.model = ets(train_data, lambda = "auto")
summary(ets.model)
```


```{r}
checkresiduals(ets.model)
```
```{r}
ets.predict=forecast(ets.model,h=24)
autoplot(ets.predict)
```

```{r}
autoplot(ets.predict) + autolayer(test_data) + ggtitle("ETS model Predict")
```

```{r}
autoplot(test_data) +
  autolayer(ets.predict$mean, series="ETS Model") +
  ggtitle("Forecast Wind Speed for 2020-2021.") +
  xlab("Year") + ylab("Speed")
```

```{r}
accuracy(ets.predict$mean, test_data)
```

### VAR Model
```{r}
var.model <- VAR(cbind(t_train, train.agg.at),p = 1, type = "both",season="12")
coef(var.model)
```

```{r}
var.predict <- predict(var.model, n.ahead = 24)
```

```{r}
 VARselect(cbind(t_train, train.agg.at), lag.max = 10, type = "both",season="12")
```

```{r}
plot(var.predict)
```

```{r}
p1<-ts(var.predict$fcst$t_train[,1],start=c(2020,1),end=c(2021,12),frequency=12)
```

```{r}
autoplot(test_data) +
  autolayer(InvBoxCox(p1, lambda_train), series="VAR",) +
  ggtitle("Forecast Wind Speed for 2020-2021.") +
  xlab("Year") + ylab("Speed")
```

```{r}
accuracy(InvBoxCox(var.predict$fcst$t_train[,1], lambda_train), test_data)
```


```{r}
checkresiduals(var.model$varresult$t_train)
```

```{r}
serial.test(var.model, lags.pt=10, type="PT.asymptotic")
```

```{r}
plot(resid(var.model))
```


```{r}
plot(resid(var.model), ylim=c(-10,10))
abline(0,1)
```



